targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          generate_for:
            - lib/**
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
          include_if_null: false
      freezed:
        options:
          map: true
          when: true
          maybe_when: true 